---
output: 
  html_document
params:
  Set_Title: "Insert Report Title here"
  Annotations:
    label: "Go-Terms:"
    value: GO_OI.xlsx
    input: file
  Type:
    label: "Go-Terms:"
    value: Total
    choices: [Total, Slim]
  Data: 
    label: "Input dataset:"
    value: POI.xlsx
    input: file
title: "`r params$set_title`"
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r library_loading, include=FALSE}

##pacman is like a package for package management

if (!require("pacman")) install.packages("pacman", repos = 'http://cran.us.r-project.org')
library(pacman)

#https://miktex.org/download
#if (!require("packrat")) install.packages("packrat", repos = 'http://cran.us.r-project.org')
#library(packrat)

### installing other packages
pacman::p_load_gh("krlmlr/here" ,  dependencies = TRUE)
pacman::p_load("readr","tidyverse", "openxlsx", "stringr", "ontologyIndex", "biomaRt",
               "data.table","BiocManager","devtools", "shiny","DT", "RCurl", update = FALSE)

devtools::install_github("jimhester/archive")
#needed for readGAF, and GoAnnotations, installable through BiocManager
BiocManagerlibraries <- c("biomaRt","org.Hs.eg.db") #"clusterProfiler","pathview",

for (i in BiocManagerlibraries){
if (!requireNamespace(i, quietly = TRUE))
    BiocManager::install(i)
    library(i, character.only = T )
}
```

```{r file loading and pre-processing, include=FALSE}

#here::set_here()
#GO_annotations <- read.xlsx("./../Project_Datasets/GO_annotations.xlsx")

###unzips the .7z and loads it
Human_Proteins <- archive::archive_read("./../Project_Datasets/HUMAN_9606_idmapping.7z")%>% read_tsv(col_names = FALSE) %>% 
  setNames(c("Uniprot", "Type", "Value"))

#15.01.2019    ConsensusPathDB version 34 has been released.
#loads all the consensusDB, keeps high confidence and NA and penalises complexes 1/n
#this ensures that a protein isn't getting a lot of GO terms from a single complex
ConsensusDB_PPI <- read_tsv("./../Project_Datasets/ConsensusPathDB_human_PPI") %>% 
  dplyr::filter((interaction_confidence>0.5 | is.na(interaction_confidence)) & str_detect(.$interaction_participants,",")) 
 
ConsensusDB_PPI$interaction_confidence[is.na(ConsensusDB_PPI$interaction_confidence)] <- ConsensusDB_PPI$interaction_participants[is.na(ConsensusDB_PPI$interaction_confidence)] %>%
  str_count(pattern = ",") %>% (function(x) 1/(x-1))

ConsensusDB_PPI <- ConsensusDB_PPI[!(ConsensusDB_PPI$interaction_confidence == Inf),]

#list of all interactors
ConsensusDB_PPIs <- sapply(ConsensusDB_PPI$interaction_participants, function(x) str_split(x, pattern = ","))
# Human_Proteins <- read_tsv("./../Project_Datasets/HUMAN_9606_idmapping.dat", col_names = FALSE) %>%
#  setNames(c("Uniprot", "Type", "Value"))
```

```{r Converting Input, include=FALSE}
#### ______________ Input_file_name_____############
#direct_input
POI_list <- read.xlsx("./../Project_Datasets/POIS.xlsx", colNames = F)$X1
Go_terms_OI <- read.xlsx("./../Project_Datasets/Go_terms_OI.xlsx", colNames = F)$X1 %>% append("GO:0005634")
gm_attribute_input <- "go_id"
gm_second_attribute_input <- "name_1006"

##user_input
# Go_terms_OI <- read.xlsx(params$Annotations, colNames = F)$X1
# POI_list <- read.xlsx(params$Data, colNames = F)$X1
# gm_attribute_input <- if_else(params$Type == "Total", "go_id", "goslim_goa_accession")
# gm_second_attribute_input <- if_else(params$Type == "Total", "name_1006", "goslim_goa_description")




Uniprot_Conversion <- function(x){
  All_uniprots <- table(Human_Proteins$Uniprot[Human_Proteins$Value == x]) 
  names(which(All_uniprots == max(All_uniprots, na.rm = T)))
  
}

Converted <- sapply(POI_list, try(Uniprot_Conversion))
Converted <- data.frame(Name_provided = names(Converted), 
                             Uniprot = as.character(Converted),
                             stringsAsFactors = F)

Converted <- dplyr::left_join(Converted,dplyr::filter(Human_Proteins, 
                                        Human_Proteins$Uniprot %in% Converted$Uniprot &
                                        Human_Proteins$Type == "UniProtKB-ID"), 
                       by = "Uniprot") %>% tidyr::drop_na()


```

```{r Getting Go terms and producing Output, include=FALSE}
mart <- try(useMart(biomart = "ensembl", dataset = "hsapiens_gene_ensembl"))

###getHandleRcurl https://csbi.ltdk.helsinki.fi/meap/anduril/doc/components/BiomartAnnotator/BiomartAnnotator.r
### finding the number of hits for all Go-terms of interest together for each protein in the list
POI_Go_detection <- function(x){
  print(x)
  results <- getBM(attributes = c(gm_attribute_input, "name_1006" ) , filters = "uniprotswissprot",
           values = x , mart = mart, curl=curlHandle)
  list(counts =
  mean(str_count(results[,1], paste(Go_terms_OI,collapse = "|")), na.rm = T),
  all_terms = results,
  matched_terms = paste(results[results[,1] %in% Go_terms_OI,2], collapse = ",")
  
  )
  }
Converted$GO_POI <- NA
Converted$POI_Go_found <- NA
Converted$All_Go <- NA
curlHandle <- getCurlHandle()

j <- 1
while(j <= nrow(Converted)){
    try(Go_terms_found <- POI_Go_detection(Converted$Uniprot[j]))->doStuffResults
    if(class(doStuffResults) != "try-error"){
      Converted$GO_POI[j] <- Go_terms_found$counts
      print(Converted$Name_provided[j])
      if(!rlang::is_empty(Go_terms_found$matched_terms)){
        Converted[j , "POI_Go_found"][1] <- list(Go_terms_found$matched_terms)
        Converted[j , "All_Go"][[1]] <- list(Go_terms_found$all_terms)
      }
      j <- j + 1
      }
}

if(nrow(Converted)>500){
  Converted <- Converted[with(Converted,order(GO_POI,decreasing = T)),]%>%
    .[1:500,]
}

# Counting_Go_terms_OI <- function(getBM_results, Partner_swissport){
#   ID <- Human_Proteins$Value[Human_Proteins$Type == "UniProtKB-ID" & Human_Proteins$Uniprot == Partner_swissport]
#   dplyr::filter(results_1, uniprotswissprot == "O00264")[,1]
# }

### finding secondary interaction partners and their matching Goterms
PP_Go_detection <- function(x){
  #x = Converted$Value[3]
  print(x)
  Protein_ConsensusDB_PPI <-  subset(ConsensusDB_PPI, str_detect(ConsensusDB_PPI$interaction_participants, pattern = x))
  PPI1s <- Protein_ConsensusDB_PPI$interaction_participants %>% str_split(pattern = ",")  %>% unlist() %>% unique() %>% .[. != x]
  
  Uniprots_PPI1 <- Human_Proteins[Human_Proteins$Value %in% PPI1s, -2]
  
  PPI2s <- str_subset(ConsensusDB_PPI$interaction_participants, pattern = paste(PPI1s,collapse="|")) %>%
    str_split(pattern = ",")  %>% unlist() %>% unique() %>% .[!(. %in% PPI1s)]
  
  Uniprots_PPI2 <- Human_Proteins[Human_Proteins$Value %in% PPI2s, -2]
  
  results_1 <- getBM(attributes = c(gm_attribute_input, gm_second_attribute_input ,'uniprotswissprot'), filters = "uniprotswissprot",
           values = Uniprots_PPI1$Uniprot , mart = mart, curl=curlHandle)
  
  results_2 <- getBM(attributes = c(gm_attribute_input, gm_second_attribute_input ,"uniprotswissprot"), filters = "uniprotswissprot",
           values = Uniprots_PPI2$Uniprot, mart = mart, curl=curlHandle)
  
  
  #### Creates nested df for each Partner and calcuates the percentage of Go hits out of all go terms for each protein
  results_1 <- results_1 %>% nest(data = -uniprotswissprot) %>% 
    dplyr::left_join(Human_Proteins[Human_Proteins$Type == "UniProtKB-ID", -2], by = c("uniprotswissprot" = "Uniprot")) %>%
    mutate(count = sapply(.$data, function(x) mean(unlist(x) %in% Go_terms_OI, na.rm = T)))
  
  results_2 <- results_2 %>% nest(data = -uniprotswissprot) %>% 
    dplyr::left_join(Human_Proteins[Human_Proteins$Type == "UniProtKB-ID", -2], by = c("uniprotswissprot" = "Uniprot")) %>%
    mutate(count = sapply(.$data, function(x) mean(unlist(x) %in% Go_terms_OI, na.rm = T)))
  
  
  PPI1 <-    data.table(Value = x, Partners = PPI1s, PP_Type = "Primary") %>% left_join(results_1, by = c("Partners" = "Value"))
  PPI2 <-    data.table(Value = x, Partners = PPI2s, PP_Type = "Secondary") %>% left_join(results_2, by = c("Partners" = "Value"))
  
  
  #### retrieves mean confidence for each partnter
  PPI1$Confidence <-  sapply(PPI1$Partners, function(x) mean(Protein_ConsensusDB_PPI$interaction_confidence[str_detect(Protein_ConsensusDB_PPI$interaction_participants, x)],
                                                 na.rm = T), simplify = T)
  
  PPI_primary_confidence <- ConsensusDB_PPI[str_detect(ConsensusDB_PPI$interaction_participants, paste(PPI1$Parterns,collapse = "|")),3:4]
  PPI2$Confidence <-  as.vector(sapply(PPI2$Partners, function(x) mean(PPI_primary_confidence$interaction_confidence[str_detect(PPI_primary_confidence$interaction_participants, x)],na.rm = T)/50, simplify = T))
  
  combined_PPI1_PPI2 <- rbind(PPI1, PPI2)  %>%
    mutate(Adjusted_hits = count*Confidence )
}
Converted$Partners <- NA
Converted$PPI_rank <- NA
### find the number of partners and their Go-terms, and the number of match
count <- 1
for (i in Converted$Value[(count):nrow(Converted)]){
  n <- 0
  while(n<5){
   print(count)
   df <- try(PP_Go_detection(Converted$Value[i]), silent=TRUE)
  if(!is(df, 'try-error')){
    Converted[count,"Partners"][[1]] <- list(df)
    Converted$PPI_rank[count] <- sum(Converted[count,"Partners"][[1]]$Adjusted_hits, na.rm = T)
    count <- count+1
    break
  }
   else{
     print(df)
     n <- n+1
   }
  }
}
#PP_detected$Normalised_Count <- PP_detected$Go_count*
#Converted <- dplyr::left_join(Converted,PP_detected %>% nest(data = -Value), by = "Value")
#Converted <- dplyr::left_join(Converted,Human_Proteins[Human_Proteins$Type == "GeneID",c(1,3)],  by = 'Uniprot')

# for (i in 1:nrow(Converted)){
#   Uniprots <- Human_Proteins$Uniprot[Human_Proteins$Value %in% Converted$PPI1[[i]]] 
#   Converted$PPI1_gene_ids[i] <- list(Human_Proteins$Value[Human_Proteins$Uniprot %in% Uniprots & Human_Proteins$Type == "GeneID"])
# }

Converted <- 
  getBM(attributes=c('uniprotswissprot','description'), filters = 'uniprotswissprot',
        values = Converted$Uniprot, mart =mart) %>%
  dplyr::left_join(Converted,by =c("uniprotswissprot" = "Uniprot"))

Converted <- Converted[with(Converted,order(GO_POI,PPI_rank, decreasing = T)),]

columns_of_interest <- c("uniprotswissprot", "description", "Name_provided", "GO_POI","POI_Go_found", "Value", "PPI_rank") 
Converted_noPartners <- Converted[,columns_of_interest]

saveRDS(Converted, file = "./../Project_Output/Nested_Final_Ouput.rds")


list_POI_Go <- Converted$All_Go
names(list_POI_Go) <- Converted$Value

write.xlsx(list_POI_Go,"./../Project_Output/POIs_All_GOs.xlsx")

list_Partners_Go <- Converted$Partners
names(list_Partners_Go) <- Converted$Value

write.xlsx(list_Partners_Go,"./../Project_Output/POI_PPIs.xlsx")
write.xlsx(Converted_noPartners,"./../Project_Output/POIs_sorted.xlsx")
```

```{r}
DT::datatable(Converted_noPartners)

```

<button class="btn btn-primary" data-toggle="collapse" data-target="#BlockName"> `r Converted$Value[1]` </button>  
<div id="BlockName" class="collapse">


```{r}
DT::datatable(Converted[1, "Partners"][[1]][,-5])

```

</div>

<button class="btn btn-primary" data-toggle="collapse" data-target="#BlockName1"> `r Converted$Value[2]` </button>  
<div id="BlockName1" class="collapse"> 


```{r}
DT::datatable(Converted[2, "Partners"][[1]][,-5])
```

</div>

<button class="btn btn-primary" data-toggle="collapse" data-target="#BlockName2"> `r Converted$Value[3]` </button>  
<div id="BlockName2" class="collapse">  


```{r}
DT::datatable(Converted[3, "Partners"][[1]][,-5])
```

</div>

<button class="btn btn-primary" data-toggle="collapse" data-target="#BlockName3"> `r Converted$Value[4]` </button>  
<div id="BlockName3" class="collapse">


```{r}
DT::datatable(Converted[4, "Partners"][[1]][,-5])

```

</div>

<button class="btn btn-primary" data-toggle="collapse" data-target="#BlockName4"> `r Converted$Value[5]` </button>  
<div id="BlockName4" class="collapse"> 


```{r}
DT::datatable(Converted[5, "Partners"][[1]][,-5])
```

</div>

<button class="btn btn-primary" data-toggle="collapse" data-target="#BlockName5"> `r Converted$Value[6]` </button>  
<div id="BlockName5" class="collapse">  


```{r}
DT::datatable(Converted[6, "Partners"][[1]][,-5])
```

</div>

<button class="btn btn-primary" data-toggle="collapse" data-target="#BlockName6"> `r Converted$Value[7]` </button>  
<div id="BlockName6" class="collapse">


```{r}
DT::datatable(Converted[7, "Partners"][[1]][,-5])

```

</div>

<button class="btn btn-primary" data-toggle="collapse" data-target="#BlockName7"> `r Converted$Value[8]` </button>  
<div id="BlockName7" class="collapse"> 




```{r}
DT::datatable(Converted[8, "Partners"][[1]][,-5])
```

</div>

<button class="btn btn-primary" data-toggle="collapse" data-target="#BlockName8"> `r Converted$Value[9]` </button>  
<div id="BlockName8" class="collapse">  


```{r}
DT::datatable(Converted[9, "Partners"][[1]][,-5])
```

</div>

<button class="btn btn-primary" data-toggle="collapse" data-target="#BlockName9"> `r Converted$Value[10]` </button>  
<div id="BlockName9" class="collapse">  


```{r}
DT::datatable(Converted[10, "Partners"][[1]][,-5])
```

</div>

